server.port: 8443

server.ssl.enabled: false
# server.ssl.key-store: file:/etc/cas/thekeystore
# server.ssl.key-store: classpath:thekeystore
# server.ssl.key-store-password: changeit
# server.ssl.key-password: changeit

# Enable HTTP connections for the embedded Tomcat container
cas.server.http.port: 8088
cas.server.http.protocol: org.apache.coyote.http11.Http11NioProtocol
cas.server.http.enabled: true

# Use HTTP and IP access
cas.server.name: http://127.0.0.1:8088
cas.server.prefix: http://127.0.0.1:8088/cas

cas.tgc.secure: false

# Auto-initialize the registry from default JSON service definitions
cas.serviceRegistry.initFromJson: true

#logging.config: file:/etc/cas/config/log4j2.xml
#logging.config: classpath:log4j2.xml

# Configure admin pages
cas.adminPagesSecurity.actuatorEndpointsEnabled: true
cas.monitor.endpoints.enabled: true
endpoints.enabled: true

cas.monitor.endpoints.sensitive: false
endpoints.sensitive: false

cas.adminPagesSecurity.ip: 127\.0\.0\.1
cas.adminPagesSecurity.loginUrl: ${cas.server.prefix}/login
cas.adminPagesSecurity.service: ${cas.server.prefix}/status/dashboard
cas.adminPagesSecurity.users: classpath:admin-users.properties
cas.adminPagesSecurity.adminRoles[0]: ROLE_ADMIN

##
# CAS Authentication Credentials
#
cas.authn.accept.users: casuser::Mellon

#---------------
#cas.authn.accept.users: 

# cas.authn.jdbc.query[0].user: root
# cas.authn.jdbc.query[0].password: root
# cas.authn.jdbc.query[0].driverClass: com.mysql.jdbc.Driver
# cas.authn.jdbc.query[0].url: jdbc:mysql://127.0.0.1:3306/rtms?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_general_ci&autoReconnect=true&useSSL=false
# cas.authn.jdbc.query[0].dialect: org.hibernate.dialect.MySQLDialect
#---------------

# cas.authn.jdbc.query[0].failFastTimeout: 1
# cas.authn.jdbc.query[0].isolationLevelName: ISOLATION_READ_COMMITTED
# cas.authn.jdbc.query[0].healthQuery: 
# cas.authn.jdbc.query[0].isolateInternalQueries: false
# cas.authn.jdbc.query[0].leakThreshold: 10
# cas.authn.jdbc.query[0].propagationBehaviorName: PROPAGATION_REQUIRED
# cas.authn.jdbc.query[0].batchSize: 1
# cas.authn.jdbc.query[0].defaultCatalog: 
# cas.authn.jdbc.query[0].defaultSchema: 
# cas.authn.jdbc.query[0].ddlAuto: create-drop

# cas.authn.jdbc.query[0].autocommit: false
# cas.authn.jdbc.query[0].idleTimeout: 5000

# cas.authn.jdbc.query[0].dataSourceName: 
# cas.authn.jdbc.query[0].dataSourceProxy: false

# Hibernate-specific properties (i.e. `hibernate.globally_quoted_identifiers`)
# cas.authn.jdbc.query[0].properties.propertyName: propertyValue

# cas.authn.jdbc.query[0].pool.suspension: false
# cas.authn.jdbc.query[0].pool.minSize: 6
# cas.authn.jdbc.query[0].pool.maxSize: 18
# cas.authn.jdbc.query[0].pool.maxWait: 2000
# cas.authn.jdbc.query[0].pool.timeoutMillis: 1000

#---------------
#cas.authn.jdbc.query[0].sql: SELECT pass FROM User WHERE name = ?
#cas.authn.jdbc.query[0].fieldPassword: pass
#---------------

# cas.authn.jdbc.query[0].fieldExpired: 
# cas.authn.jdbc.query[0].fieldDisabled: 
# cas.authn.jdbc.query[0].principalAttributeList: sn,cn:commonName,givenName

#---------------
#cas.authn.jdbc.query[0].passwordEncoder.type: DEFAULT
#cas.authn.jdbc.query[0].passwordEncoder.characterEncoding: UTF-8
#cas.authn.jdbc.query[0].passwordEncoder.encodingAlgorithm: MD5
#---------------
