server.port: 8443

# server.ssl.key-store: file:/etc/cas/thekeystore
server.ssl.key-store: classpath:thekeystore
server.ssl.key-store-password: changeit
server.ssl.key-password: changeit

# Enable HTTP connections for the embedded Tomcat container
cas.server.http.port: 8080
cas.server.http.protocol: org.apache.coyote.http11.Http11NioProtocol
cas.server.http.enabled: true

# Use HTTP and IP access
cas.server.name: http://127.0.0.1:8080
cas.server.prefix: http://127.0.0.1:8080/cas

cas.tgc.secure: false

# Auto-initialize the registry from default JSON service definitions
cas.serviceRegistry.initFromJson: true

#logging.config: file:/etc/cas/config/log4j2.xml
#logging.config: classpath:log4j2.xml

# Configure admin pages
cas.adminPagesSecurity.actuatorEndpointsEnabled: true
cas.monitor.endpoints.enabled: true
endpoints.enabled: true

cas.monitor.endpoints.sensitive: false
endpoints.sensitive: false

cas.adminPagesSecurity.ip: 127\.0\.0\.1
cas.adminPagesSecurity.loginUrl: ${cas.server.prefix}/login
cas.adminPagesSecurity.service: ${cas.server.prefix}/status/dashboard
cas.adminPagesSecurity.users: classpath:admin-users.properties
cas.adminPagesSecurity.adminRoles[0]: ROLE_ADMIN

##
# CAS Authentication Credentials
#
# cas.authn.accept.users: casuser::Mellon

